[package]
name = "gravlox"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
env_logger = { version = "0.11.8", features = ["kv"] }
log = { version = "0.4.27", features = ["kv"] }
pico-args = "0.5.0"
rustc-hash = "2.1.1"
